# Generated by Django 4.1.3 on 2023-01-25 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userinformation_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinformation',
            old_name='user',
            new_name='author',
        ),
    ]
