# Generated by Django 4.1.3 on 2023-01-25 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_user_userinformation_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinformation',
            name='id',
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
