# Generated by Django 4.1.3 on 2023-01-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_userinformation_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinformation',
            name='name',
        ),
        migrations.AddField(
            model_name='userinformation',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='Profile_image'),
        ),
    ]
