# Generated by Django 4.1.3 on 2023-01-15 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_blog_options_rename_time_blog_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='assets/topic3.png', upload_to='Blog_Image/'),
        ),
    ]
